name: Build Gradle Project

on:
  push:
  pull_request:

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 18
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set gradlew executable
        run: chmod +x gradlew
      - name: Generate AST
        uses: gradle/gradle-build-action@v2
        with:
          arguments: generateAstShell
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test